version: "3.8" # Docker Compose 파일 버전

networks:
  hyeseon:  # 네트워크 정의
    driver: bridge

services:
  frontend:
    build:
      context: ./final-pjt-front # 프론트엔드 Dockerfile 위치
    command: http-server -a 0.0.0.0 -p 5173 --cors
    ports:
      - "5173:5173" # 포트 매핑 설정
    networks:
      - hyeseon

  backend:
    build:
      context: ./final-pjt-back # 백엔드 Dockerfile 위치
    ports:
      - "8080:8080" # 포트 매핑 설정
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker 소켓 마운트
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ssafy_project?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: ssafy
#      SPRING_DATASOURCE_PASSWORD: ssafy
      CORS_ALLOWED_ORIGIN: http://13.124.154.154:5173
    networks:
      - hyeseon

networks:
  hyeseon:
    external: true 
